//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheeseWorldMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheeseWorld_DatabaseEntities1 : DbContext
    {
        public CheeseWorld_DatabaseEntities1()
            : base("name=CheeseWorld_DatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblCheese> tblCheese { get; set; }
        public DbSet<tblCheeseRating> tblCheeseRatings { get; set; }
        public DbSet<tblCoupon> tblCoupons { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblDiscount> tblDiscounts { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblMeat> tblMeats { get; set; }
        public DbSet<tblMeatRating> tblMeatRatings { get; set; }
        public DbSet<tblMiscProduct> tblMiscProducts { get; set; }
        public DbSet<tblMiscRating> tblMiscRatings { get; set; }
        public DbSet<tblNew> tblNews { get; set; }
        public DbSet<tblReservation> tblReservations { get; set; }
        public DbSet<tblSpecial> tblSpecials { get; set; }
        public DbSet<tblSubscription> tblSubscriptions { get; set; }
        public DbSet<tblTransaction> tblTransactions { get; set; }
    }
}
