//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheeseWorldMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblCheeseRatings = new HashSet<tblCheeseRating>();
            this.tblMeatRatings = new HashSet<tblMeatRating>();
            this.tblMiscRatings = new HashSet<tblMiscRating>();
            this.tblReservations = new HashSet<tblReservation>();
            this.tblSubscriptions = new HashSet<tblSubscription>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerStreetAddress { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public Nullable<decimal> CustomerPhone { get; set; }
        public Nullable<int> CustomerZipCode { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPassword { get; set; }
    
        public virtual ICollection<tblCheeseRating> tblCheeseRatings { get; set; }
        public virtual ICollection<tblMeatRating> tblMeatRatings { get; set; }
        public virtual ICollection<tblMiscRating> tblMiscRatings { get; set; }
        public virtual ICollection<tblReservation> tblReservations { get; set; }
        public virtual ICollection<tblSubscription> tblSubscriptions { get; set; }
    }
}
