//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheeseWorldMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscount
    {
        public tblDiscount()
        {
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public int DiscountID { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
    
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
