//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheeseWorldMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeat
    {
        public tblMeat()
        {
            this.tblMeatRatings = new HashSet<tblMeatRating>();
            this.tblReservations = new HashSet<tblReservation>();
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public int MeatID { get; set; }
        public string MeatName { get; set; }
        public Nullable<decimal> MeatCostPrice { get; set; }
        public Nullable<decimal> MeatQuantity { get; set; }
        public string MeatProvider { get; set; }
        public Nullable<System.DateTime> MeatPurchaseDate { get; set; }
        public Nullable<System.DateTime> MeatExpirationDate { get; set; }
        public Nullable<decimal> MeatRetailPrice { get; set; }
        public Nullable<decimal> MeatScore { get; set; }
        public string MeatDescription { get; set; }
        public string MeatType { get; set; }
    
        public virtual ICollection<tblMeatRating> tblMeatRatings { get; set; }
        public virtual ICollection<tblReservation> tblReservations { get; set; }
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
