//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheeseWorldMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNew
    {
        public int newsID { get; set; }
        public string NewsHeadline { get; set; }
        public string NewsContent { get; set; }
        public string NewsStatus { get; set; }
    }
}
