//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheeseWorldMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpecial
    {
        public int SpecialID { get; set; }
        public string SpecialHeadline { get; set; }
        public string SpecialContent { get; set; }
        public string SpecialStatus { get; set; }
    }
}
