//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheeseWorldMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Coupons { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> CheeseID { get; set; }
        public Nullable<int> MeatID { get; set; }
        public Nullable<int> MiscProductID { get; set; }
        public Nullable<int> CouponID { get; set; }
        public string transactionItem { get; set; }
    
        public virtual tblCheese tblCheese { get; set; }
        public virtual tblCoupon tblCoupon { get; set; }
        public virtual tblDiscount tblDiscount { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblMeat tblMeat { get; set; }
        public virtual tblMiscProduct tblMiscProduct { get; set; }
    }
}
